### ISSUE TITLE
Response Type for `ListSessions()` missing

### ISSUE THREAD

**Issue by darmiel** [SkYNewZ/go-flaresolverr#1]
`ListSessions()` returns `*Response` which doesn't contain a `sessions` field, which is returned when requesting the sessions.
https://github.com/FlareSolverr/FlareSolverr#-sessionslist

### How to reproduce

```go
cf := flaresolverr.New("http://127.0.0.1:8191/v1", 60*time.Second, http.DefaultClient)

resp, err := cf.ListSessions(context.TODO())
if err != nil {
	panic(err)
}

// cannot access `sessions`
resp.Sessions
```

### Possible Fix

**a) Extend `*Response` to include the `Sessions` field**

```go
type Response {
  // ...
  Sessions []uuid.UUID `json:"sessions"`
}
```

**b) Create new response type for `ListSessions()`**

**Comment by SkYNewZ** [comment]
Hello. Thank you for using this library. I took the opportunity to refactor it a bit, that should fix your issue. Don't hesitate to keep me informed !

**Comment by darmiel** [comment]
Thank you for the quick fix! 🙂
